const tintColorLight = '#B01A1D';
const tintColorDark = '#E63B3E';

export default {
  light: {
    text: '#000000',
    background: '#F5F5F5',
    tabBackground: '#FFFFFF',
    tint: tintColorLight,
    tabIconDefault: '#7D7D7D',
    tabIconSelected: tintColorLight,
    accent: tintColorLight,
    border: '#E0E0E0',
    cardBackground: '#FFFFFF',
    safe: '#2D8632',
    euclid: '#F6C844',
    keter: '#B01A1D',
    thaumiel: '#4A56B7',
    neutralized: '#7D7D7D',
    explained: '#7D7D7D',
    esoteric: '#7A4988',
    archon: '#FF6B6B',
    apollyon: '#1A1A1A',
    ticonderoga: '#4ECDC4',
    cernunnos: '#45B7AF',
  },
  dark: {
    text: '#FFFFFF',
    background: '#121212',
    tabBackground: '#1E1E1E',
    tint: tintColorDark,
    tabIconDefault: '#A7A7A7',
    tabIconSelected: tintColorDark,
    accent: tintColorDark,
    border: '#333333',
    cardBackground: '#1E1E1E',
    safe: '#4CAF50',
    euclid: '#FFD54F',
    keter: '#E63B3E',
    thaumiel: '#5C6BC0',
    neutralized: '#9E9E9E',
    explained: '#9E9E9E',
    esoteric: '#9C64A6',
    archon: '#FF7F7F',
    apollyon: '#000000',
    ticonderoga: '#5DDED6',
    cernunnos: '#4EC9C0',
  },
};